### ISSUE TITLE
Mismatch between GetTemplateByName and GetAllTemplates

### ISSUE THREAD

**Issue by Oddsor** [ardoq/ardoq-csharp-client#8]
A bug was reported regarding these two functions, and it seems like they filter search results by different criteria!

GetAllTemplates filters by `m.UseAsTemplate == true`, while GetTemplateByName skips this check. Results in weird scenarios where you won't find templates when getting "all" templates, but still find templates when you add a name!

See:
https://github.com/ardoq/ardoq-csharp-client/blob/8f0e128fcd5ad11ccccadd4b3693cc404240b8d4/Ardoq/Service/ModelService.cs#L35

https://github.com/ardoq/ardoq-csharp-client/blob/8f0e128fcd5ad11ccccadd4b3693cc404240b8d4/Ardoq/Service/ModelService.cs#L48

This issue is mainly about identifying which of the two lines must be updated. An issue reported by a user suggests we may simply need to remove the UseAsTemplate-check from GetAllTemplates.

**Comment by Oddsor** [comment]
We have to figure out what the expectations are for these functions. The confusion seems to be about what "all templates" are. We also should clarify if these functions should include "common" templates ("includeCommon=true" in the model api-call)

**Comment by dknn** [comment]
I would like to be able to get ALL templates, is common the templates that is installed/maintained by ardoq?  Also I think this test needs to be updated https://github.com/ardoq/ardoq-csharp-client/blob/master/ArdoqTests/Service/ModelServiceTest.cs 
 (wait until you have decided on what default behavior should be)

**Comment by Oddsor** [comment]
I think we will end up changing GetTemplateByName to also filter on "UseAsTemplate == true". This would suggest that the initial bug @nls75 reported is actually that you got a result from GetTemplateByName that you shouldn't have, as it should be a subset of GetAllTemplates!

To replicate the old functionality of GetTemplateByName I think a GetModelByName is needed.

**Comment by Oddsor** [comment]
We may also need to change GetTemplateByName and GetModelByName to return a collection of Models, because it is actually possible for multiple models/ to have the same name!

The fact that they return a single element is just confusing to users, giving the impression that names are unique.

**Comment by Oddsor** [comment]
FYI @nls75 : I believe the real bug here was that GetAllTemplates never returned anything. Pull request #9 should fix this.

Also consider pull request #11 which adds more sane convenience functions for getting template/model by name
